In [2]:
import torch
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using mps device


In [6]:
A = torch.arange(6).reshape(2,3)
B = torch.ones(2,3)
A,B

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [5]:
A+B

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
A+3

tensor([[3, 4, 5],
        [6, 7, 8]])

In [8]:
A*B

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [9]:
A.sum()

tensor(15)

In [10]:
A.sum(axis=0)

tensor([3, 5, 7])

In [14]:
torch.mm(A,A.T)

tensor([[ 5, 14],
        [14, 50]])

In [16]:
x = torch.tensor([-3.0,4.0])
torch.norm(x)

tensor(5.)

In [17]:
x = torch.tensor([[3.0,4.0],[1.0,2.0]])
torch.norm(x)

tensor(5.4772)

In [18]:
x = torch.ones(2,3,4)
len(x)
torch.randn

2