In [1]:
import torch

In [4]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)

In [6]:
print(x.grad)

None


In [11]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [12]:
print(x.grad)

None


In [13]:
y.backward()
print(x.grad)

tensor([ 4.,  8., 12.])


In [14]:
x.grad.zero_()
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [15]:
y.backward()
x.grad

tensor([1., 1., 1.])

In [20]:
x.grad.zero_()
y = x * x
y

tensor([1., 4., 9.], grad_fn=<MulBackward0>)

In [21]:
y.backward(gradient=torch.ones(len(y)))
x.grad

tensor([2., 4., 6.])

In [22]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([2., 4., 6.])

In [23]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [28]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a.grad

tensor(2048.)

In [37]:
a = torch.tensor([2.0,3.0,100.0], requires_grad=True)
d = f(a)
print(d)
d.backward(gradient=torch.ones(len(a)))
a.grad

tensor([  32.,   48., 1600.], grad_fn=<MulBackward0>)


tensor([16., 16., 16.])

In [57]:
w = torch.tensor([1.0,2.0], requires_grad=True)
y = w * w
y.backward(gradient=torch.ones(len(w)))
w.grad

tensor([2., 4.])

In [59]:

with torch.no_grad():
  w -= 2
w

tensor([-1.,  0.], requires_grad=True)

In [60]:
w.grad

tensor([2., 4.])