In [2]:
import pandas as pd
import torch

In [4]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.shape

torch.Size([12])

In [6]:
x.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
torch.randn((3,4),dtype=torch.float64)

tensor([[ 0.2313, -0.8979,  0.0097, -0.6156],
        [ 1.1573,  1.6373,  0.7392,  0.4872],
        [ 0.8745, -1.0227,  0.7260, -2.5667]], dtype=torch.float64)

In [3]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [11]:
x[:,-1]

tensor([ 3,  6,  9, 12])

In [14]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
torch.argmax(x,dim=1)

tensor([2, 2, 2, 2])

In [15]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
torch.sum(torch.square(x))

tensor(650)

In [19]:
x = torch.zeros([2,4])
x.dtype

torch.float32

In [22]:
def _relu(x):
        return x * (x > 0)

In [24]:
x = torch.tensor([1,2,3, -0.2, 0.2])
_relu(x)

tensor([1.0000, 2.0000, 3.0000, -0.0000, 0.2000])

In [25]:
torch.nn.functional.relu(x)

tensor([1.0000, 2.0000, 3.0000, 0.0000, 0.2000])

In [9]:
import torch
x = torch.tensor([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x.shape)
batch_size = 4
batches = x.shape[0]
for i in range(0,batches,batch_size):
    print(x[i:i+batch_size])

torch.Size([5, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[ 9, 10]])
